version: '3.3'

services:
  world-start-api:
    container_name: world-start-api
    build:
      context: .
      dockerfile: Dockerfile
    # command: gunicorn world.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - api_code:/usr/src/app'
    networks:
      - world-stats
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - world-start-api-db

  world-start-api-db:
    container_name: world-start-api-db
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    networks:
    - world-stats
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
  api_code:

networks:
  world-stats:
    external:
      name: world-stats