version: '3'

services:
  api:
    container_name: api
    build:
      context: ./services/api
      dockerfile: Dockerfile
    # command: gunicorn world.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - api_code:/usr/src/app'
    ports:
      - '80:80'
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  # nginx:
  #   container_name: nginx
  #   build: ./services/nginx
  #   restart: always
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - api
  #     - client
  #   links:
  #     - api
  # client:
  #   container_name: client
  #   build:
  #     context: ./services/client
  #     dockerfile: Dockerfile.prod
  #     args:
  #       - NODE_ENV=development
  #   volumes:
  #     - '.:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=development

volumes:
  postgres_data:
  api_code:
