version: '3.3'

services:

  api:
    container_name: api
    build:
      context: ./services/api
      dockerfile: Dockerfile-dev
    command: gunicorn world.wsgi.application --bind 0.0.0.0:8000
    volumes:
      - './services/api:/usr/src/app'
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: ./services/api/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=world
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db:
    image: postgres:12.0-alpine
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  nginx:
    container_name: nginx
    build: ./services/nginx
    restart: always
    ports:  
      - 80:80
    depends_on:
      - api
      - client
    links:
      - api

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
    ports:
      - '3007:3000' 
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    links:
      - api

volumes:
  postgres_data: