# Generated by Django 3.0.6 on 2020-05-06 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('countrycode', models.CharField(max_length=3)),
                ('district', models.TextField()),
                ('population', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('continent', models.TextField()),
                ('region', models.TextField()),
                ('surfacearea', models.FloatField()),
                ('indepyear', models.SmallIntegerField(blank=True, null=True)),
                ('population', models.IntegerField()),
                ('lifeexpectancy', models.FloatField(blank=True, null=True)),
                ('gnp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gnpold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('localname', models.TextField()),
                ('governmentform', models.TextField()),
                ('headofstate', models.TextField(blank=True, null=True)),
                ('code2', models.CharField(max_length=2)),
                ('capital', models.ForeignKey(blank=True, db_column='capital', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.City')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('countrycode', models.OneToOneField(db_column='countrycode', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Country')),
                ('language', models.TextField()),
                ('isofficial', models.BooleanField()),
                ('percentage', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Country Languages',
                'db_table': 'countrylanguage',
                'unique_together': {('countrycode', 'language')},
            },
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(check=models.Q(continent__in=['Asia', 'Europe', 'North America', 'Africa', 'Oceania', 'Antarctica', 'South America']), name='country_continent_check'),
        ),
    ]
