# Generated by Django 3.0.6 on 2020-05-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrylanguage',
            name='countrycode',
            field=models.ForeignKey(db_column='countrycode', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Country'),
        ),
    ]
