# Generated by Django 3.0.6 on 2020-05-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200506_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrylanguage',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countrylanguage',
            name='countrycode',
            field=models.ForeignKey(db_column='countrycode', on_delete=django.db.models.deletion.CASCADE, to='api.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='countrylanguage',
            unique_together=set(),
        ),
    ]
