# Generated by Django 3.0.6 on 2020-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200506_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrylanguage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
